sudo: false
language: elixir
elixir:
  - 1.6.0
  - 1.5.0
  - 1.4.0
  - 1.3.0

jobs:
  include:
    - stage: deploy
      otp_release: 19.3
      script: skip
      deploy:
        provider: script
        script: ./scripts/hexpub.sh
        skip_cleanup: true
        on:
          tags: true
